--- a/decoupled/60/0.8_0.2/180/pytest-dev_pytest/testing/python/collect.py
+++ b/decoupled/60/0.8_0.2/180/pytest-dev_pytest/testing/python/collect.py
@@ -1191,32 +1191,7 @@
 

 

 @pytest.mark.filterwarnings("default")

-def test_dont_collect_non_function_callable(testdir):

-    """Test for issue https://github.com/pytest-dev/pytest/issues/331

-

-    In this case an INTERNALERROR occurred trying to report the failure of

-    a test like this one because pytest failed to get the source lines.

-    """

-    testdir.makepyfile(

-        """

-        class Oh(object):

-            def __call__(self):

-                pass

-

-        test_a = Oh()

-

-        def test_real():

-            pass

-    """

-    )

-    result = testdir.runpytest()

-    result.stdout.fnmatch_lines(

-        [

-            "*collected 1 item*",

-            "*test_dont_collect_non_function_callable.py:2: *cannot collect 'test_a' because it is not a function*",

-            "*1 passed, 1 warning in *",

-        ]

-    )

+...

 

 

 def test_class_injection_does_not_break_collection(testdir):
